extends: eslint:all

env:
    node: true
    es6: true

rules:
    complexity:
        - warn
        - 10
    dot-location:
        - error
        - property
    func-style:
        - error
        - declaration
    guard-for-in: off
    id-match:
        - error
        - ^[a-zA-Z]+$
    max-len:
        - error
        - 120
    max-nested-callbacks:
        - error
        - 2
    no-console: off
    no-magic-numbers:
        - error
        - ignoreArrayIndexes: true
          enforceConst: true
    no-underscore-dangle:
        - error
        - allow:
            - _id
    one-var:
        - error
        - never
    padded-blocks:
        - error
        - never
    quotes:
        - error
        - single
    quote-props:
        - error
        - as-needed
    spaced-comment:
        - error
        - always
        - markers:
            - '*'
    valid-jsdoc:
        - error
        - prefer:
            return: returns
            method: function
            func: function
            arg: param
            argument: param
            prop: property
