env:
    node: true
    es6: true

rules:
    # Possible Errors
    comma-dangle: error
    no-cond-assign: error
    no-console: off
    no-constant-condition: error
    no-control-regex: error
    no-debugger: error
    no-dupe-args: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-empty-character-class: error
    no-empty: error
    no-ex-assign: error
    no-extra-boolean-cast: error
    no-extra-parens: error
    no-extra-semi: error
    no-func-assign: error
    no-inner-declarations: error
    no-invalid-regexp: error
    no-irregular-whitespace: error
    no-negated-in-lhs: error
    no-obj-calls: error
    no-regex-spaces: error
    no-sparse-arrays: error
    no-unexpected-multiline: error
    no-unreachable: error
    no-unsafe-finally: error
    use-isnan: error
    valid-jsdoc:
        - error
        - prefer:
            return: returns
            method: function
            func: function
            arg: param
            argument: param
            prop: property
    valid-typeof: error

    # Best Practices
    accessor-pairs: error
    array-callback-return: error
    block-scoped-var: off # no-var
    complexity:
        - warn
        - 10
    consistent-return: error
    curly: error
    default-case: off
    dot-location:
        - error
        - property
    dot-notation: error
    eqeqeq: error
    guard-for-in: off # no-extend-native
    no-alert: off # env: node
    no-caller: error
    no-case-declarations: error
    no-div-regex: error
    no-else-return: error
    no-empty-label: off # no-labels
    no-empty-function: error
    no-empty-pattern: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: off # no-labels
    no-fallthrough: error
    no-floating-decimal: error
    no-implicit-globals: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    no-labels: error
    no-lone-blocks: error
    no-loop-func: off # no-var
    no-magic-numbers:
        - error
        - ignoreArrayIndexes: true
          enforceConst: true
    no-multi-spaces: error
    no-multi-str: error
    no-native-reassign: error
    no-new-func: error
    no-new-wrappers: error
    no-new: error
    no-octal-escape: error
    no-octal: error
    no-param-reassign: warn
    no-process-env: error
    no-proto: error
    no-redeclare: error
    no-return-assign: error
    no-script-url: error
    no-self-assign: error
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: error
    no-unused-expressions: error
    no-unused-labels: off # no-labels
    no-useless-call: error
    no-useless-concat: error
    no-useless-escape: error
    no-void: error
    no-warning-comments: warn
    no-with: error
    radix: error
    vars-on-top: off # no-var
    wrap-iife: error
    yoda: error

    # Strict Mode
    strict:
        - error
        - global

    # Variables
    init-declarations: off
    no-catch-shadow: error
    no-delete-var: error
    no-label-var: off # no-labels
    no-restricted-globals: off # none
    no-shadow-restricted-names: error
    no-shadow: error
    no-undef: error
    no-undefined: error
    no-unused-vars: error
    no-use-before-define:
        - error
        - nofunc

    # Node.js
    callback-return: error
    global-require: error
    handle-callback-err: error
    no-mixed-requires: off # one-var
    no-new-require: error
    no-path-concat: error
    no-process-exit: error
    no-restricted-imports: off # none
    no-restricted-modules: off # none
    no-sync: error

    # Stylistic Issues
    array-bracket-spacing: error
    block-spacing: error
    brace-style: error
    camelcase:
        - error
        - properties: always
    comma-spacing: error
    comma-style: error
    computed-property-spacing: error
    consistent-this: error
    eol-last: error
    func-names: error
    func-style:
        - error
        - declaration
    id-length:
        - error
    id-match:
        - error
        - ^[a-zA-Z]+$
    id-blacklist: off # none
    indent:
        - error
        - 4
    jsx-quotes: off # no jsx
    key-spacing: error
    keyword-spacing: error
    linebreak-style: error
    lines-around-comment: off # don't care
    max-depth: error
    max-len:
        - error
        - 120
    max-nested-callbacks:
        - error
        - 2
    max-params: error
    max-statements: error
    max-statements-per-line: error
    new-cap: error
    new-parens: error
    newline-after-var: error
    newline-before-return: error
    newline-per-chained-call: error
    no-array-constructor: error
    no-bitwise: error
    no-continue: error
    no-inline-comments: error
    no-lonely-if: error
    no-mixed-spaces-and-tabs: error
    no-multiple-empty-lines: error
    no-negated-condition: error
    no-nested-ternary: off # no-ternary
    no-new-object: error
    no-plusplus: error
    no-restricted-syntax: off # none
    no-whitespace-before-property: error
    no-spaced-func: error
    no-ternary: error
    no-trailing-spaces: error
    no-underscore-dangle:
        - error
        - allow:
            - _id
    no-unneeded-ternary: off # no-ternary
    object-curly-spacing: error
    one-var:
        - error
        - never
    one-var-declaration-per-line: off # one-var
    operator-assignment: error
    operator-linebreak: error
    padded-blocks:
        - error
        - never
    quote-props:
        - error
        - as-needed
    quotes:
        - error
        - single
    require-jsdoc: error
    semi-spacing: error
    semi: error
    sort-vars: off # one-var
    sort-imports: off # none
    space-before-blocks: error
    space-before-function-paren: error
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment:
        - error
        - always
        - markers:
            - '*'
    wrap-regex: error

    # ECMAScript 6
    arrow-body-style:
        - error
        - always
    arrow-parens: error
    arrow-spacing: error
    constructor-super: error
    generator-star-spacing:
        - error
        - both
    no-class-assign: error
    no-confusing-arrow: error
    no-const-assign: error
    no-dupe-class-members: error
    no-duplicate-imports: off # none
    no-new-symbol: error
    no-this-before-super: error
    no-useless-computed-key: error
    no-useless-constructor: error
    no-var: error
    object-shorthand: error
    prefer-arrow-callback: error
    prefer-const: error
    prefer-reflect: error
    prefer-rest-params: error
    prefer-spread: error
    prefer-template: error
    require-yield: error
    template-curly-spacing: error
    yield-star-spacing:
        - error
        - both
