language: node_js
node_js: iojs-2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libc6
      - lcov

services:
  - mongodb

before_script:
  - export CC=/usr/bin/gcc-4.9
  - export CXX=/usr/bin/g++-4.9
