language: node_js
node_js: 6

before_install:
  - npm i -g npm@5
  - npm i -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

cache:
  directories:
    - $HOME/.npm
