version: '2'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest@sha256:482a562bf25f42f02ce589458f72866bbe9eded5b6f8fa5b1213313f0e00bba2
