version: '2'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest@sha256:5d7043a4ffe02b9ed1b6e0bab057546981af5ca0a79107e9c461e49bc44c0a7b
