version: '2'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest@sha256:9342a9279a9841fc5f8192e49dcaaf9404e6bb3a90e8cf134eb96074830dd448
