version: '2'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest@sha256:2609aaf7a1abbff404101af896e05f243d22be742471ed857b50b9ce0270fdbd
