version: '2'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest@sha256:3a09cd85fb4e76f1d5832f9ea1d4e7481f76e807389b7d8ea6ac4d4ba96f83e5
