env:
    node: false
    es6: false
    browser: true
    jquery: true

rules:
    strict:
        - error
        - function
    no-var: off
    object-shorthand: off
    prefer-arrow-callback: off
    prefer-template: off
