env:
    node: false
    es6: false
    browser: true
    jquery: true

rules:
    strict:
        - 2
        - function
    no-var: 0
    object-shorthand: 0
    prefer-arrow-callback: 0
    prefer-template: 0
