rules:
    camelcase: off
    max-nested-callbacks:
        - error
        - 3
    max-params:
        - error
        - 10
    max-statements:
        - error
        - 15
    no-magic-numbers: off
